source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'motioncamea_Example', :exclusive => true do
  pod 'motioncamea', :path => '../'
end

target 'motioncamea_Tests', :exclusive => true do
  pod 'motioncamea', :path => '../'

  
end
